.TH "gnome-lirc-properties" 1
.SH NAME
gnome-lirc-properties \- A control panel to configure remote controls.
.SH SYNOPSIS
.B gnome-lirc-properties
.SH DESCRIPTION
This control panel updates lirc's configuration files to match your choices.
It also allows editing, uploading and downloading of custom remote control
configuration files.

.SH AUTHORS
Written by Murray Cumming and Mathias Hasselmann..

.SH "SEE ALSO"
The full documentation for the
.B gnome-lirc-properties
command is available in the GNOME help system: <ghelp:gnome-lirc-properties>.

.SH "PROJECT PAGE"
The project page is available at <https://code.fluendo.com/remotecontrol/trac/>.

