"""
Configuration information.
Generated by config.status from config.py.in.
"""

from os                        import path

ENABLE_POLICY_KIT     = True
POLICY_KIT_ACTION     = 'org.gnome.lirc-properties.mechanism.configure'

PACKAGE_DIR           = path.join('/usr', 'share', 'gnome-lirc-properties')

LIRC_CONFDIR          = '/etc/lirc/'
LIRCD_SOCKET          = '/var/run/lirc/lircd'

LIRC_HARDWARE_CONF    = '/etc/sysconfig/lirc'
LIRC_REMOTE_CONF      = path.join(LIRC_CONFDIR, 'lircd.conf.gnome')
LIRC_DAEMON_CONF      = path.join(LIRC_CONFDIR, 'lircd.conf')

LIRC_REMOTES_DATABASE = '/usr/share/lirc-remotes/'
LIRC_IRRECORD         = '/usr/bin/irrecord'

LIRC_INPUT_DRIVER     = 'devinput'

STARTUP_STYLE         = 'fedora'

# remove temporary objects from namespace
del path
